/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Benji' at '7/30/16 9:07 AM' with Gradle 2.10
 *
 * @author Benji, @date 7/30/16 9:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
